# Generated by Django 4.0 on 2022-01-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='stockquantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='valume',
            field=models.IntegerField(null=True),
        ),
    ]
