# Generated by Django 4.0 on 2022-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_details', '0002_details_stockquantity_details_valume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='costperitem',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stockquantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='valume',
            field=models.BigIntegerField(null=True),
        ),
    ]
